version: "2"

services:
  valleyn-web3-test-server:
    container_name: valleyn-web3-test-server
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8081:8081

    volumes:
      - type: bind
        source: .
        target: /valleyn-web3-test-server
      - /valleyn-web3-test-server/node_modules
    command: npm run start:dev
    environment:
      PORT: 8081

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
    command: config --json API.HTTPHeaders.Access-Control-Allow-Origin  '["http://localhost:3000", "http://localhost:3001"]'
    command: daemon
    
