version: "2"

services:
  valleyn-web3-test-server:
    container_name: valleyn-web3-test-server
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8081:8081

    volumes:
      - type: bind
        source: .
        target: /valleyn-web3-test-server
      - /valleyn-web3-test-server/node_modules
    command: npm run start:dev
    environment:
      PORT: 8081

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
    command: config --json API.HTTPHeaders.Access-Control-Allow-Origin  '["http://localhost:3000", "http://localhost:3001"]'
    command: daemon
  
  testdb:
   container_name: testdb
   image: mysql/mysql-server:5.7
   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: develop
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   volumes:
     - /var/lib/mysql
    
